{
    "attributes": {
        "self": "https://api.tempo.io/[...]",
        "values": []
    },
    "author": {
        "accountId": "123456:01234567-89ab-cdef-0123-456789abcdef",
        "self": "https://api.tempo.io/[...]"
    },
    "billableSeconds": 100201,
    "createdAt": "2017-02-06T16:41:41.000Z",
    "description": "Investigating a problem with our external database system",
    "issue": {
        "id": 124,
        "self": "https://api.tempo.io/[...]"
    },
    "self": "https://api.tempo.io/[...]",
    "startDate": "2019-08-24",
    "startDateTimeUtc": "2017-02-05T16:06:00.000Z",
    "startTime": 72360,
    "tempoWorklogId": 126,
    "timeSpentSeconds": 3600,
    "updatedAt": "2017-02-06T16:41:41.000Z"
}
